name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  parse-and-lint:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    env:
      DBT_TARGET: ci
      SNOWFLAKE_ACCOUNT: dummy
      SNOWFLAKE_USER: dummy
      SNOWFLAKE_DATABASE: dummy
      SNOWFLAKE_PRIVATE_KEY_PATH: dummy
      DBT_CI_SCHEMA: dummy

    steps:
      - name: Checkout steam-analytics onto the runner
        uses: actions/checkout@v4 

      - name: Set up python environment
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: pip 

      - name: Install python packages
        run: pip install -r requirements.txt 

      - name: Install dbt packages 
        run: dbt deps 

      - name: Run dbt parse
        run: dbt parse

      - name: Run sqlfluff linter 
        run: sqlfluff lint .

  dbt-run:
    needs: parse-and-lint
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      actions: read
      contents: read

    env: 
      DBT_TARGET: ci
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE  }}
      DBT_CI_SCHEMA: ci_pr_${{ github.event.pull_request.number }}

    steps:
      - name: Checkout steam-analytics onto the runner
        uses: actions/checkout@v4 

      - name: Set up python environment
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
          cache: pip 

      - name: Install python packages
        run: pip install -r requirements.txt 

      - name: Install dbt packages 
        run: dbt deps 

      - name: Write private Snowflake key to runner disk
        env:
          SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
        run: |
          printf '%s' "$SNOWFLAKE_PRIVATE_KEY" > "$RUNNER_TEMP/snowflake_private_key.p8"
          chmod 600 "$RUNNER_TEMP/snowflake_private_key.p8"
          echo "SNOWFLAKE_PRIVATE_KEY_PATH=$RUNNER_TEMP/snowflake_private_key.p8" >> "$GITHUB_ENV"

      - name: Download latest latest prod manifest.json 
        uses: dawidd6/action-download-artifact@v6 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: update-dbt-artifacts-and-docs.yml
          workflow_conclusion: success
          branch: main 
          name: dbt-manifest
          path: state

      - name: Run dbt build against prod
        run: dbt build --select state:modified+ --defer --state state

      - name: Drop the ci_pr_* schema made from dbt build 
        if: always()
        run: dbt run-operation drop_ci_schema 

